server:
  port: 9000
spring:

  application:
    name: runninginformationanalysisservice
  datasource:
    url: jdbc:mysql://localhost:3306/private
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
